server:
  port: 0

spring:
  application:
    name: thicket-member

  profiles:
    active: localDB, mail
    include: secret

  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driver-class-name: ${localDB.driver}
    username: ${localDB.username_}
    password: ${localDB.password}
    url: ${localDB.url}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.web: DEBUG

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka

