server:
  port: 0

spring:
  application:
    name: thicket-show

  profiles:
    active: localDB, s3key

  datasource:
    driver-class-name: ${localDB.driver}
    username: ${localDB.username_}
    password: ${localDB.password}
    url: ${localDB.url}

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    org.springframework.web: DEBUG

cloud:
  aws:
    s3:
      bucket: ${s3key.bucket}
    stack:
      auto: false
    region:
      static: ${s3key.region}
    credentials:
      accessKey: ${s3key.accessKey}
      secretKey: ${s3key.secretKey}

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka